variable "region" {
  default = "us-east-1"
}
variable "bucket_name" {
  default = "srk-msk-143"
}
variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}
